import "./globals.css";
import { Inter, Roboto } from "next/font/google";

const font = Inter({ weight: "200", subsets: ["latin"] });
// const font = Roboto({ weight: "300", subsets: ["latin"] });

export const metadata = {
  title: "Bookmarks",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-screen">
      <body
        className={font.className + " h-screen text-sm"}
        suppressHydrationWarning={true}
      >
        {children}
      </body>
    </html>
  );
}
